### ISSUE TITLE
WordPress iframe not showing up with shortcode.

### ISSUE THREAD

**Issue by mrkillertoast** [alextselegidis/easyappointments-wordpress-plugin#14]
Hey i want to thanke you for your greate work. But unfortunatly i am facing the Problem that nothing is showing up on the Page. Could you please help me? I am using the latest Wordpress version. Thanks in advance.

**Comment by alextselegidis** [comment]
Hello!

Although this is an older ticket, whenever there's no iframe showing or its contents are wrong there is an underlying Easy!Appointments connection problem. 

Head to the Settings > Easy!Appointments page and make sure that the URL you've set there points to an Easy!Appointments installation. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
![Screenshot 2020-10-26 at 12 03 35](https://user-images.githubusercontent.com/4527441/97159305-52aa9e00-1783-11eb-94ce-f533935c77d6.png)
