### ISSUE TITLE
Plugin not available from wordpress plugin directory

### ISSUE THREAD

**Issue by hkotka** [alextselegidis/easyappointments-wordpress-plugin#6]
Hi, plugin seems to not be currently available from wordpress plugin directory. https://wordpress.org/plugins/easyappointments returns not found page.

**Comment by alextselegidis** [comment]
The plugin has become available again in the plugin directory.

Thanks for posting :)

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
